# Generated by Django 4.0.4 on 2022-06-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_book_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.category')),
            ],
        ),
    ]
