# Generated by Django 4.0.4 on 2022-06-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_bookcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategories',
            new_name='BookCategory',
        ),
    ]
