# Generated by Django 4.0.4 on 2022-06-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_delete_bookcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks', to='app_api.order'),
        ),
    ]
